<a href="https://colab.research.google.com/github/SkinnySanti/AnaliticaDeDatos/blob/main/Limpieza_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Proceso de limpieza y analisis**

1.Preparamos los datos

2.Exploramos los datos

3.Eliminamos los datos

4.Normalizamos los datos

5.Correjimos los datos

6.Exportamos los datos

**LIBRERIAS UTILIZADAS**

pandas

numpy

plotty

In [ ]:
import pandas as pd
import plotly.express as px

In [ ]:
# Esta linea de codigo ordena al lenguaje que lea el archivo que le estamos pasando
#df => significa dataframe
df = pd.read_excel("Movilidad_U_Quindio.xlsx")

In [ ]:
#Verificamos que el archivo este correcto
df.shape

(2741, 11)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2741 entries, 0 to 2740
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Periodo                         2741 non-null   object
 1   Cargo                           2741 non-null   object
 2   Facultad/Dependencia            2741 non-null   object
 3   Programa/Oficina                2741 non-null   object
 4   Nombre de la actividad General  2741 non-null   object
 5   Origen                          2741 non-null   object
 6   Ciudad de Origen                2741 non-null   object
 7   Institución de Origen           2731 non-null   object
 8   Movilidad                       2741 non-null   object
 9   Tipo                            2741 non-null   object
 10  Destino                         2741 non-null   object
dtypes: object(11)
memory usage: 235.7+ KB

In [ ]:
df

,Periodo,Cargo,Facultad/Dependencia,Programa/Oficina,Nombre de la actividad General,Origen,Ciudad de Origen,Institución de Origen,Movilidad,Tipo,Destino
0,2019-2,Docente visitante,Ingenieria,Ingenieria Civil,Gestión academica para el programa de Inegnier...,Alemania,Eberswalde,Universidad Eberswalde,Asistencia a Eventos,Entrante,Internacional
1,2019-2,Estudiante,Ciencias de la Salud,Medicina,Rotación Medica,Alemania,Leipzig,Universidad de Leipzig,Rotacion Medica,Saliente,Internacional
2,2019-2,Docente,Ciencias de la Salud,Medicina,Pasantia Internacional,Alemania,Duisburg,University of Duisburg,Ponencia,Saliente,Internacional
3,2019-2,Personal Administrativo,Vicerrectoria Academica,Admisiones y Registro,Reconocer y Analizar el proceso de trasnferenc...,Antioquia,Medellin,Universidad de Antioquia,Asistencia a Eventos,Saliente,Nacional
4,2019-2,Estudiante,Ciencias Economicas y Adtivas,Admon Financiera,Ponentes en el primer encuentro nacional de se...,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
...,...,...,...,...,...,...,...,...,...,...,...
2736,2019-2,Docente,Ciencias Humanas y Bellas Artes,Trabajo Social,"participacion como coordinadora de la mesa ""vi...",Valle del Cauca,santiago de cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2737,2019-2,Personal Administrativo,Vicerrectoria Academica,Unidad de Virtualizacion,Implementación de la primera versión del labor...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2738,2019-2,Personal Administrativo,Vicerrectoria Academica,Unidad de Virtualizacion,Taller de socialización y construcción,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2739,2019-2,Vicerrectoria Académica,Rectoria,Vicerrectoria Academica,Foro Internacional Sobre Inclusión y Equidad e...,Valle del Cauca,Cali,UNESCO,Asistencia a Eventos,Saliente,Nacional
2740,2019-2,Docente visitante,Ingenieria,Ingenieria Civil,Realizar actividades de cooperación academica,Venezuela,Caracas,Universidad Central de Venezuela,Asistencia a Eventos,Entrante,Internacional

In [ ]:
#ETAPA DE EXPLORACION
df.head(20)

,Periodo,Cargo,Facultad/Dependencia,Programa/Oficina,Nombre de la actividad General,Origen,Ciudad de Origen,Institución de Origen,Movilidad,Tipo,Destino
0,2019-2,Docente visitante,Ingenieria,Ingenieria Civil,Gestión academica para el programa de Inegnier...,Alemania,Eberswalde,Universidad Eberswalde,Asistencia a Eventos,Entrante,Internacional
1,2019-2,Estudiante,Ciencias de la Salud,Medicina,Rotación Medica,Alemania,Leipzig,Universidad de Leipzig,Rotacion Medica,Saliente,Internacional
2,2019-2,Docente,Ciencias de la Salud,Medicina,Pasantia Internacional,Alemania,Duisburg,University of Duisburg,Ponencia,Saliente,Internacional
3,2019-2,Personal Administrativo,Vicerrectoria Academica,Admisiones y Registro,Reconocer y Analizar el proceso de trasnferenc...,Antioquia,Medellin,Universidad de Antioquia,Asistencia a Eventos,Saliente,Nacional
4,2019-2,Estudiante,Ciencias Economicas y Adtivas,Admon Financiera,Ponentes en el primer encuentro nacional de se...,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
5,2019-2,Estudiante,Ciencias Economicas y Adtivas,Admon Financiera,Ponentes en el primer encuentro nacional de se...,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
6,2019-2,Estudiante,Ciencias Economicas y Adtivas,Admon Financiera,Ponentes en el primer encuentro nacional de se...,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
7,2019-2,Docente,Ciencias Economicas y Adtivas,Admon Financiera,I Encuentro nacional de Semilleros de Investig...,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
8,2019-2,Personal Administrativo,Vicerrectoria Academica,Biblioteca,Segundo encuentro Presencial del programa pilo...,Antioquia,Medellin,EAFIT,Asistencia a Eventos,Saliente,Nacional
9,2019-2,Personal Administrativo,Vicerrectoria Adtiva,Bienestar,Comité Nacional de Cultura ASCUN,Antioquia,Medellin,ASCUN,Asistencia a Eventos,Saliente,Nacional
10,2019-2,Personal Administrativo,Vicerrectoria Adtiva,Bienestar,Bases para la definición de lineamientos que o...,Antioquia,Medellin,Universidad CES,Asistencia a Eventos,Saliente,Nacional
11,2019-2,Docente,Ciencias Basicas y Tecnologias,Biologia,Asistir al 46 Congreso de Entomología,Antioquia,Medellin,Universidad Nacional,Asistencia a Eventos,Saliente,Nacional
12,2019-2,Docente,Ciencias Basicas y Tecnologias,Biologia,Asistir al laboratorio de Microscopía TEM,Antioquia,Medellin,Universidad de Antioquia,Asistencia a Eventos,Saliente,Nacional
13,2019-2,Docente,Ciencias Basicas y Tecnologias,Biologia,Semillero de Investigación BIO,Antioquia,Medellin,Universidad de Antioquia,Asistencia a Eventos,Saliente,Nacional
14,2019-2,Estudiante,Ciencias Basicas y Tecnologias,Biologia,Asistir al 46 Congreso de Entomología,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
15,2019-2,Estudiante,Ciencias Basicas y Tecnologias,Biologia,Asistir al 46 Congreso de Entomología,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
16,2019-2,Estudiante,Ciencias Basicas y Tecnologias,Biologia,Asistir al 46 Congreso de Entomología,Antioquia,Medellin,Universidad Nacional,Ponencia,Saliente,Nacional
17,2019-2,Estudiante,Ciencias Basicas y Tecnologias,Biologia,Asistir al 46 Congreso de Entomología,Antioquia,Medellin,Universidad Nacional,Asistencia a Eventos,Saliente,Nacional
18,2019-2,Estudiante,Ciencias Basicas y Tecnologias,Biologia,Asistir al 46 Congreso de Entomología,Antioquia,Medellin,Universidad Nacional,Asistencia a Eventos,Saliente,Nacional
19,2019-2,Estudiante,Ciencias Basicas y Tecnologias,Biologia,Asistir al 46 Congreso de Entomología,Antioquia,Medellin,Universidad Nacional,Asistencia a Eventos,Saliente,Nacional

In [ ]:
#Nos muestra los datos de los ultimos valores
df.tail(20)

,Periodo,Cargo,Facultad/Dependencia,Programa/Oficina,Nombre de la actividad General,Origen,Ciudad de Origen,Institución de Origen,Movilidad,Tipo,Destino
2721,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2722,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2723,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2724,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2725,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2726,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2727,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2728,2019-2,Estudiante,Ciencias de la Salud,Seguridad y Salud en el Trabajo,Salida de Campo a la casa Grajales,Valle del Cauca,La Union,Casa Grajales,Salida de Campo,Saliente,Nacional
2729,2019-2,Docente,Ciencias Humanas y Bellas Artes,Trabajo Social,Asistir al II Coloqui nacional de estudios de ...,Valle del Cauca,Cali,Universidad del Valle,Ponencia,Saliente,Nacional
2730,2019-2,Estudiante,Ciencias Humanas y Bellas Artes,Trabajo Social,Participar en el II Colowuio de estudios de ge...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2731,2019-2,Estudiante,Ciencias Humanas y Bellas Artes,Trabajo Social,Participar en el II Colowuio de estudios de ge...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2732,2019-2,Estudiante,Ciencias Humanas y Bellas Artes,Trabajo Social,Participar en el II Colowuio de estudios de ge...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2733,2019-2,Estudiante,Ciencias Humanas y Bellas Artes,Trabajo Social,Participar en el II Colowuio de estudios de ge...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2734,2019-2,Estudiante,Ciencias Humanas y Bellas Artes,Trabajo Social,Participar en el II Colowuio de estudios de ge...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2735,2019-2,Estudiante,Ciencias Humanas y Bellas Artes,Trabajo Social,Participar en el II Colowuio de estudios de ge...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2736,2019-2,Docente,Ciencias Humanas y Bellas Artes,Trabajo Social,"participacion como coordinadora de la mesa ""vi...",Valle del Cauca,santiago de cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2737,2019-2,Personal Administrativo,Vicerrectoria Academica,Unidad de Virtualizacion,Implementación de la primera versión del labor...,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2738,2019-2,Personal Administrativo,Vicerrectoria Academica,Unidad de Virtualizacion,Taller de socialización y construcción,Valle del Cauca,Cali,Universidad del Valle,Asistencia a Eventos,Saliente,Nacional
2739,2019-2,Vicerrectoria Académica,Rectoria,Vicerrectoria Academica,Foro Internacional Sobre Inclusión y Equidad e...,Valle del Cauca,Cali,UNESCO,Asistencia a Eventos,Saliente,Nacional
2740,2019-2,Docente visitante,Ingenieria,Ingenieria Civil,Realizar actividades de cooperación academica,Venezuela,Caracas,Universidad Central de Venezuela,Asistencia a Eventos,Entrante,Internacional

In [ ]:
#Nos indica los valores que mas se repiten
df["Nombre de la actividad General"].describe()

count                                              2741
unique                                              638
top       Jornada Academica Centro Recreacional Tulaima
freq                                                108
Name: Nombre de la actividad General, dtype: object

In [ ]:
#Mostramos los datos unicos
df["Nombre de la actividad General"].unique()

array(['Gestión academica para el programa de Inegniería Forestal',
       'Rotación Medica', 'Pasantia Internacional',
       'Reconocer y Analizar el proceso de trasnferencia digital en los grados',
       'Ponentes en el primer encuentro nacional de semilleros',
       'I Encuentro nacional de Semilleros de Investigación',
       'Segundo encuentro Presencial del programa piloto laboratorio para la Innovación Educativa',
       'Comité Nacional de Cultura ASCUN',
       'Bases para la definición de lineamientos que orientan la construcción de protocolos dirigidos a la prevención y atención de casos de violencia',
       'Asistir al 46 Congreso de Entomología',
       'Asistir al laboratorio de Microscopía TEM',
       'Semillero de Investigación BIO',
       'Salida al Laboratorio de Microscopía TEM',
       'Conocer estrategia de transformación digital con algunos procesos de secretaria general',
       'Invitado Semana de la Comunicación',
       'Conferencista de la Expedición Visual',
       'XXXV Simposio de la ecuela de ciencias sociales',
       'Festival Gabriel García Marquez de Periodismo Versión 2019',
       'Talleres, Conferencias y Actividades del Festival Gabriel García Marquez de Periodismo Versión 2019',
       'Promocionar el doctorado en ciencias y crear vinculos academicos',
       'Asistir al curso de citometria de flujo',
       'Conferencista I Simposio Uniquindiano de Economia',
       'IV Congreso Nacional y V Congreso de atención al paciente con heridas',
       'XXIX Encuentro nacional de estudiantes de enfermerá',
       '31 Congreso Colombiano de Pediatría|',
       'III Congreso Internacional de Investigación Lingüística',
       'II Encuentro nacional de Gerentología',
       'Asistir al evento programado por el CNA y la (acofi)',
       'Asistir al foro:Lineamientos para acreditación de programas',
       'Asistencia al primer encuentro de la alianza Seneca',
       'XIV Seminario de Tuneles y Obras Subterraneas SAI-ACTOS',
       'Asistir al Taller Resultados de aprendizaje para programas de Ingeniería',
       'Participar en el encuentro dinamizador nacional de la UNEES',
       'Desplazamiento De Los Estudiantes El Espacio Academico Aep (Practica Empresarial) A La Ciudad De Medellin  Con El Fin De Asistir Al Evento: Iv Seminario De Tuneles Y Obras Subterraneas, Sai-Actos.',
       'Par academico Universidad de Antioquia',
       'IV Congreso Internacional de Investigación en Calidad',
       'XII Seminario Internacional de Ciencias de la Computaciòn',
       'asistir a los siguientes eventos: Participación en el XII SEMINARIO INTERNACIONAL DE CIENCIAS DE LA COMPUTACIÓN ( SICC 2019',
       'Seminario de desarrollo Porfesoral',
       'Ponente en el III Congreso internacional de investigación lingüística',
       'Orientar modulo de Gestión de proyectos de Sofware',
       'Asistir a la celebración de 50 años del herbario',
       'Asistir encuentro latinoamericano de educación ELE',
       'VIII Encuentro Colombiano de Gestión Universitaria',
       'Estancia Investigativa en el GAF',
       'Visita tecnica a la empresa EPM', 'Visita tecnica Empresa EPM',
       'Apertura del Foro de Trabajo Social',
       'Debate sobre la calidad de la educación a distancia,virtual en trabajo social',
       'Asistir al seminario Internacional,etica intercultural y decolonial en trabajo social',
       'Coloquio Internacional Sobre Violencia y sus Discursividades',
       'XIX Convención Nacional ASCEMCOL',
       'Capacitación en el tercer congreso internacional en la gestion del riesgo de desastres',
       'Seminario Internacional Etica intercultural y Decolonial desde el Trabajo social',
       'Seminario Internacional Etica Intercultural y Decolobial en el Trabajo Social',
       'Segunda sesión de la red academica por el derecho humano',
       'Conferencia en el tema de posgrados',
       'Conferencía enseñar de la relación pedagogica para formar competencias',
       'Conferencía Mediación didactica en los entornos virtuales de aprendizaje',
       'Encuentro de lineamientos curriculares de los programas de posgrados',
       'I Encuentro Sostenibilidad Energética para Colombia- SÉNECA',
       'Semestre de Intercambio Internacional',
       'II Encuentro Internacional / IV Encuentro Nacional de Grupos de Investigación de la Facultad de Ciencias Económicas Administrativas y Contables"',
       'XXXII Jornadas Argentinas de Mastozoología',
       'participar del primer seminario taller “Perspectiva del sector Apícola en el Departamento del Quindío”',
       'actividades de cooperación académica con el grupo de investigación de gerencia y emprendimiento (GIGA)',
       'XVII Congreso Latinoamericano de Genética',
       'Estancia de Investigación', 'Semestre de Intercambio',
       'Estancia en el laboratorio con el fin de avanzar en el trabajo de sintesis y carecterización de materiales con propiedades superconductoras',
       'Asistir al Congreso XXI Latinoamericano y del Caribe de Ciencia y Tecnología de Alimentos',
       'X Congreso Iberoamericano deTecnologias de apoyo a la discapacidad 2019',
       'IX Simposio de Quimica Aplicada',
       'IV Encuentro Latinoamericano de profesionales docentes y estudiantes de trabajo social',
       'XXVIII Versión de los Juegos Universitarios Nacionales',
       'Coordinador Nacional de Cultura ASCUN',
       'XV Encuentro internacional de Matemáticas',
       'Par academico Verificación condiciones de calidad de Registro Calificado del Programa de Ingeniería Agroindustrial',
       'XV Encuentro Internacional de Matematicas EIMAT 2019',
       'Acompañamiento como aseora estadistica',
       'XV Ecuentro Internacional de Matematicas',
       'Orientar el Modulo Gerencia del desarrollo humano',
       'III Congreso Internacional de Educación para la primera Infancia',
       'III Encuentro del Nodo Caribe de la Red de Programas Universitarios en Familia',
       'Participar eal Hub de comercialización y transferencia de tecnología para las americas',
       'Seminario en Gerencia de Negocios Internacionales',
       'IV Congreso Internacional de Invetigación de la Red Radas',
       'XIV Congreso Colombiano de enfermedades infecciosas (CCEI)',
       'Ponente en XIII Congreso Interamericano de educadores del Area Contable',
       'XII Congreso Interamericano de Educadores del Área Contable de la AIC',
       'XXXIII Conferencia Interamericana de Contabilidad CIC',
       'III Congreso nacional prevención y cuidado de lesiones de piel',
       'III Congreso nacional de prevención y cuidado de lesiones de piel',
       'XIV Congreso Colombiano de Enfermedades Infecciosas CCEI',
       'Seminario Liderazgo Efectivo y Competencias Comportamentales para Secretarias y Tecnicos',
       'Participacion en los XXI juegos deportivos nacionales Bolivar 2019 Carlos lleras restrepo',
       'EIEI ACOFI 2019', 'Asistir EIEI ACOFI 2019',
       'Ponente en EIEI ACOFI 2019',
       'XVIII congreso Latinoamericano de Infectología Pediatrica SLIPE',
       '7 Simposio de Quimíca de Coordinación y Organometalica',
       'Ponente en el evento EIEI ACOFI-CLADI 2019',
       'Realizar actividades de cooperación academica',
       'XXXIV Congreso cientifico Internacional',
       'Asistir al simposio colombiano de biologia evolutiva colevol',
       'Maestro invitado tercer UniquindioGuit-Art Festival',
       'Taller de fortalecimiento de capacidades de manejo de colecciones biologicas',
       'VI Foro Internacional de Acreditación de EQUAA',
       'Exponer tema Actuación Practica del Gerontologo',
       'estancia Académica, que fortalezca su crecimiento profesional y académico con los contenidos temáticos proporcionados por el programa de Gerontología',
       'XXIV Encuentro Internacionak de Recia',
       'Práctica Académica Profesional en el área de investigación del Laboratorio de Post-cosecha',
       'Realizar estancia de investigación con el grupo SINFOCI',
       'Par evaluador Inertantional EQUAA en el Foro internacional de acreditación de EQUAA',
       'Rotación Médica', 'Intercambio Internacional IFMSA',
       'Salida de Campo al Departamento Administrativo Nacional de Estadistica',
       'salida empresarial con grupo de estudiantes grupo 2, de Administración de Negocios, para aplicar conocimientos adquiridos en el espacio académico de manera practica y experiencial, en la Empresa SUPER DE ALIMENTOS',
       'Visitar dos modalidades de servicios dirigidos adultos mayores',
       'Reunion de proyecto casa Luker',
       'Conferencias de Estética y Teorías de Arte Contemporáneo',
       'Salida academica  registrar los rasgos del renacimiento',
       'Brindar Capacitación y Entrenamiento de los recursos de información digital',
       'Conferemcias 2019-2 Herbario', 'Salida de campo a cenicafe',
       'I jornada Primatológica del Eje cafetero',
       'Encuentro de Asociados y Afiliados del Eje Cafetero "SINDA" 2019',
       'Reunion del comité central de doctorado en ciencias en la universidad de caldas',
       'Seminario Internacional de Artes y Humanidades',
       'Visitar Empresa Super de alimentos y laboratorio de innovación NEUROCITY',
       'Ponente en el V Foro Internacional de Responsablidad social 2019',
       'Llevar acabo los tramites relacionados con la admisión de aspirantes al Doctorado',
       'Curso de Manejo de Base de Datos, redacción y Estilo de Escritos Científicos',
       'Pasantía Nacional',
       'XIV Seminario Regional de Ciencias Biomédicas',
       'Inauguración de la cuarta cohorte del Doctorado en ciencias de la Educación CADE Quindío-RUDECOLOMBIA',
       'Reunion comité central del Doctorado',
       'Presentar seminario Titulado"actos de la conversación"',
       'I Festival Internacional de Filosofía con el Taller Titulado "Entre Musica Educación y Filosofía"',
       'Primer Internacional de filosofía',
       'Taller Fortalecimiento el enfoque de atención humanizada centrada en el paciente en las organizaciones AHCP',
       'Salida academica de practicas formativa que recibiran asistencia tecnica del ministerio de la Salud',
       'Asistencia a conservatorio sobre el futuro de la educación superior',
       'Reunión de rectores de las universidades que conforman la red Doctorado en Ciencias Biomédicas',
       'realizar una visita al observatorio vulcanológico y sismológico',
       'Reconocer el equipo de microscopia electronica y realizar análisis en la estructura del material vegetal',
       'Asistir al encuentro de asociados y afiliados del ejecafetero SINDA 2019',
       'Visita Tecnica Universidad del Cauca',
       'Practicas con pantallas HMI',
       'VIII Congreso Internacional por el Desarrollo Sostenible y Medio Ambiente',
       'I Congreso de Practica Pedagógica',
       'VI Foro de literatura"las Mujeres en la Literaruta',
       'XIII Congreso Estrategias educativas prácticas para construir un mundo mejor',
       'Asistir al VI Simposio regional de Biología',
       'Salida de campo con el fin de recolectar material botanico',
       'Visita al Herbario',
       'Taller Teorico practico denominado selección de plantas sermilleras',
       'actividades en campo de la asignatura Profundización II: Ecología del Paisaje',
       'Practicas en Laboratorio de Quimica',
       'Asistir al XIV Seminario Regional del Doctorado en Ciencias Biomédicas',
       'XIV Seminario Regional del Doctorado en Ciencias Biomedicas',
       'Visita academica', 'Visita Academica',
       'Verificar modelos Editoriales Universitarias',
       'Proceso de admisión de los aspirantes en el dostorado en Ciencias',
       'Realizaran Una Visita A La Mina La Esperanza',
       'XII Simposio Internacional de Ingenería Industrial, Actualidad y Nuevas Tendencias 2019',
       'asistir a curso de electrotecnica',
       'Practica en autómatas programables',
       'Primer Seminario de clases correspondiente al Doctorado en Estudios de Familia',
       'Asistir al segundo seminario de clases del doctorado en estudios de familia',
       'Reunión de la Red Colombiana para la Internacionalización',
       'Visita a los colegios San Luis Gonzaga y Eugenia Ravasco',
       'Realizar acercamiento para posible traslado del CAT',
       'Transportar funcionarios que van Realizar acercamiento para posible traslado del CAT',
       'Entrega de convenio interinstitucional con el colegio Santa Ines',
       'Seminario Eje Transfiere',
       'Reuniòn del consejo directivo de la fundaciòn universitaria del estado',
       'Mesas de apoyo para lista de elegibles becas de excelencia de bicentenario',
       'Asistir al II encuentro de saberes Dachi Kuita: el valor publico como construccion de paz',
       'produccion de una serie documental de productos industrializados',
       'Seminario Internacional de Investigación en Artes y Humanidades',
       'Reunión junta directiva Herbarios',
       'V Seminario Internacional en ciencias Invenstigacion y tecnologia',
       'Priemer simposio de Lianas de Colombia',
       'Pasantia de Investigación Doctoral',
       'Tercer año de los acuerdo del tratado de paz',
       'Investigación de Masozoologia',
       'coordinador en la visita de evaluacion externa al programa de contaduria publica',
       'Reunión red RAICGA',
       'I foro nacional de investigadores en profesiones de la comunicación social',
       'IV Encuentro de la Asociación Colombiana de Investigadores de Comunicación',
       'Profesor que dara el modulo emprendimiento y gestión de Organizaciones',
       '1er congreso internacional de ingenieria civil',
       'Encuentro de estudiantes por la Paz',
       '5th Workshop on ICTS for improving patients rehabilitation research techniques',
       'Seminario Nacional "Otras Voces"',
       'Ponente en el evento 5th Workshop on ICTS for improving patients rehabilitation research tecchiques',
       'I Seminario Nacional Otras Voces',
       'Ecuentro de estudiantes por la paz con la justicia social',
       'Jurado en la sustentación de tesis deñ estudianye Juan Carlos Galvis',
       'XI simposio Colombiano de Catálisis',
       'XVIII Congreso Colombiano de Quimica',
       'Poster en el Congreso Colombiano de Quimica',
       'macrojornada de socializacion convocatorias Fvtel-SGR(pacifico, eje cafetero)',
       'Octavo seminario de Tecnologias emergentes en telecomunicaciones 2019',
       'Par academico', 'Asamblea ACOFACIEN',
       'XXXIII Asamble nacional de delegados',
       'V Congreso de Estudiantes de Fiolosofia',
       'XI Congreso latinoamericano de biología matematica',
       'Asistir al XI Congreso latinoamericano de Biología Matemática Solabima 2019',
       'Poster en el XI Congreso Latinoamericano de Biologia Matematica',
       'Asistencia a Congreso', 'IX Escuela Internacional Nano Andes',
       'Asociación Colombiana de Tecnicos y Educadores de Natación',
       '"Congreso Internacional de Seguridad y Salud en el Trabajo"/"Encuentro Nacional de Comites Paritarios de Seguridad y Salud en el Trabajo"',
       'Ponente en el VII Encuentro internacional sobre estudio de fiesta nacion y cultura',
       'VII Congreso sobre manejo de ecosistemas',
       '16vo Curso Internacional de Dengue Zika y Otros Arbovirus Emergentes',
       'Taller Teórico Práctico',
       'Humanización de anticuerpos Monoclonales',
       'con el fin de realizar actividades de cooperación académica con el Centro de Investigaciones Biomédicas',
       'Realización de la Curaduría, Montaje e Inauguración de la Exposición "Amalgama"',
       'Asistir a mesa academica de la Universidad San Pablo',
       'X Encuentro Nacional de Curriculo y la Asamblea de la Asociación Red Colombiana de Facultadas de Deporte',
       'Invitación para Oferentes de programas de formación Inicas,continua y avanzada',
       'Asistir al encuentro Acceso y Excelencia a la Educación Superior',
       'Se realizarán visitas a Bolsa de Valores Colombia, Banco BBVA y Asociación Colombia Fintech.',
       'Mision academica nacional FINTECH',
       'Asistir a la mision academica FINTECH',
       'Asistir al Taller sobre aplicación del catalogo presupuestal en universidades publicas',
       'III Plenaria Nacional ASPU',
       'Asistir a la IV Plenaria Nacional de ASPU',
       'Encuentro Internacional de Bibliotecas Universitarias',
       'Primer encuentro presencial Primera version laboratorio Virtual',
       'Mesa de trabajo de diversidad e inclusion de la uniquindio y CODEAFRO',
       'VIII Curso de politicas y programas para la promocion de habitos y estilo de vida saludables',
       'Coordinador nacional de ASCUN cultura',
       'VII curso de politicas y programas para la promocion de habitos y estilos de vida saludables',
       'Asistir en calidad de representante de Decano de la facultad de ciencias basicas y tecnologicas German Dario Gomez',
       'Encuentro directores del consejo profesional de Biología',
       'VIII Simposio Colombiano de Virologia',
       'Segunda Escuela Andina de Neuroetología',
       'XXXIV congreso colombiano de fitopatologia y ciencias afines',
       'Jornada Informativa H2020 y Euraxess',
       'VII Dialogo de la investigación',
       'Reunión sobre propuesta de articulación a la gestión integral para la preservacion de la hacienda pisamal',
       'Asistrir al evento Reconocimiento a Jovenes',
       'XXXIV Congreso Colombiano de Fitopatologia y Ciencias Afines',
       'VIII Simposio Nacional y IV Congreso latinoamericano de Virologia',
       'XXXIV congreso de fitopatologia',
       '"VIII Simposio Nacional"/"IV Congreso Latinoamericano de Virologia',
       'Realizar tramites de VISA para los Estados Unidos',
       'Movilidad estudiantil, movilidad docente,practicas y pasantias,tutorias',
       'XVI Ibercom', 'II Encuentro Nacional de estudiantes de cine',
       'Foro internacional TVMORFOSIS',
       'Capacitación al grupo de contaduría internacional',
       'Participar en "Qualitative Research and critical accounting (QRCA)',
       'Encuentro Nacional Legis de Revisoría Fiscal',
       'mision academica  Nacional FINTECH',
       'X Congreso Nacional de Control interno',
       'Realizar modulo de practicas y pasantias de SAC',
       'Desarrollar Curso sobre"Tecnicas de interpretación de investagación Cualitativa Fase III"',
       'Comité curricular y autoevaluación Nacional del Doctorado RUDECOLOMBIA',
       'I Simposio Uniquindiano de Economía',
       'Participar en el concuerso olimpiadas nacionales de economía',
       'Congreso nacional de servicios ecosisteeicos 2019',
       'Congreso nacional de servicios ecosisteeicos 2020',
       'Congreso Nacional de Servicios ecosistemicos 2019',
       'Congreso Nacional de Servicios ecosistemicos 2020',
       'al XXXIV Congreso Nacional de Estudiantes de Economía',
       'Recorrido por los museos de Bogota',
       'Segundo encuentro de salud mental y I reunión nacional de formadores en salud mental',
       'XXVII Congreso internacional de metodos intermedios en epidemiologia y vigilancia en salud publica',
       'Visita de Par academico', 'Semestre de Intercambio Nacional',
       '"IX Congreso de Residentes de Pediatría"/"VII Concurso Académico"',
       'IX Congreso de Residentes de Pediatría y VII Concurso Académico',
       'IX Congreso de Presidentes de pediatrias y VII Concurso academico',
       'Ponentes en el IX Congreso de residentes en pediatria y Vi Curso academico',
       'IX Congreso en residentes en pediatria', 'Reunión ASCOFAME',
       'Proyecto titulado 876', 'Olimpiadas nacionales de filosofìa',
       'VII Congreso nacional de estudiantes de Filosofía',
       'Reunión de la Red Nacional de Programas de Filosofía',
       'XVIII Congreso Interamericano de filosofía 2019',
       'Socialización del Acuerdo Nacional Estatal y Estrategias de Seguimiento e Implementación',
       'Asistir al VII Dialogo sobre etica de la investigación dilemas y conflictos éticos',

In [ ]:
#La linea de codigo funciona para limpiar la base de datos, eliminando cualquier columna que tenga un campo de dato erroneo. Sin embargo este no lo tiene asi que decidi eliminar
data = df.drop(columns=["Origen"])

In [ ]:
#vemos que eliminamos el campo Origen
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2741 entries, 0 to 2740
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Periodo                         2741 non-null   object
 1   Cargo                           2741 non-null   object
 2   Facultad/Dependencia            2741 non-null   object
 3   Programa/Oficina                2741 non-null   object
 4   Nombre de la actividad General  2741 non-null   object
 5   Ciudad de Origen                2741 non-null   object
 6   Institución de Origen           2731 non-null   object
 7   Movilidad                       2741 non-null   object
 8   Tipo                            2741 non-null   object
 9   Destino                         2741 non-null   object
dtypes: object(10)
memory usage: 214.3+ KB

In [ ]:
data.shape

(2741, 10)

In [ ]:
data.columns

Index(['Periodo', 'Cargo', 'Facultad/Dependencia', 'Programa/Oficina',
       'Nombre de la actividad General', 'Ciudad de Origen',
       'Institución de Origen', 'Movilidad', 'Tipo', 'Destino'],
      dtype='object')

In [ ]:
#empezamos a normalizar los datos. Cambiamos el nombre de los datos porque tiene caracteres especiales
data.rename(columns={"Facultad/Dependencia": "Facultad_Dependencia",
                     "Programa/Oficina":"Programa_Oficina",
                     "Nombre de la actividad General":"Nombre_Actividad_General",
                     "Ciudad de Origen":"Ciudad_Origen",
                     "Institución de Origen":"Institucion_Origen"
                     }, inplace=True)

In [ ]:
data.columns

Index(['Periodo', 'Cargo', 'Facultad_Dependencia', 'Programa_Oficina',
       'Nombre_Actividad_General', 'Ciudad_Origen', 'Institucion_Origen',
       'Movilidad', 'Tipo', 'Destino'],
      dtype='object')

In [ ]:
data.to_excel("Movilidad_normalizado.xlsx", index=False)
print("archivo guardado")

archivo guardado

In [ ]:
px.histogram(data, x="Institucion_Origen")